<?php
/**
 * LLMS text endpoint controller class.
 *
 * @package PressAgent
 */

namespace PressAgent\Discovery;

use PressAgent\Support\Settings;

/**
 * Serves the public llms.txt endpoint.
 */
final class LlmsController {
	/**
	 * Rewrite rule for the llms.txt endpoint.
	 *
	 * @var string
	 */
	private const REWRITE_RULE = '^llms\.txt$';

	/**
	 * Query variable used by the llms.txt rewrite rule.
	 *
	 * @var string
	 */
	private const QUERY_VAR = 'pressagent_llms';

	/**
	 * Manifest instance.
	 *
	 * @var Manifest
	 */
	private Manifest $manifest;

	/**
	 * Create the controller.
	 *
	 * @param Manifest $manifest Manifest instance.
	 */
	public function __construct( Manifest $manifest ) {
		$this->manifest = $manifest;
	}

	/**
	 * Register WordPress hooks.
	 *
	 * Request recognition is always registered so the query-string fallback
	 * keeps working across enablement changes and stale rewrite rules. Only
	 * the pretty rewrite rule is conditional.
	 *
	 * @return void
	 */
	public function register_hooks(): void {
		add_filter( 'query_vars', array( $this, 'add_query_var' ) );

		/*
		 * Serve before redirect_canonical (priority 10) so extension-like
		 * paths such as /llms.txt are not 301-redirected to a slashed URL.
		 */
		add_action( 'template_redirect', array( $this, 'serve_llms' ), 1 );
		add_action( 'init', array( $this, 'add_rewrite_rule' ) );
	}

	/**
	 * Determine whether the llms.txt endpoint is enabled.
	 *
	 * @return bool Whether the endpoint is enabled.
	 */
	public static function is_enabled(): bool {
		/**
		 * Filters whether PressAgent serves its llms.txt endpoint.
		 *
		 * @since 0.1.0
		 *
		 * @param bool $enabled Whether the endpoint is enabled.
		 */
		return (bool) apply_filters( 'pressagent_llms_enabled', Settings::is_llms_enabled() );
	}

	/**
	 * Register the llms.txt rewrite rule.
	 *
	 * No rule is registered while the endpoint is disabled, so both
	 * normal loads and activation respect pressagent_llms_enabled.
	 *
	 * @return void
	 */
	public function add_rewrite_rule(): void {
		if ( ! self::is_enabled() ) {
			return;
		}

		add_rewrite_rule(
			self::REWRITE_RULE,
			'index.php?' . self::QUERY_VAR . '=1',
			'top'
		);
	}

	/**
	 * Remove the llms.txt rewrite rule.
	 *
	 * @return void
	 */
	public static function remove_rewrite_rule(): void {
		remove_rewrite_rule( self::REWRITE_RULE );
	}

	/**
	 * Register the llms.txt query variable.
	 *
	 * @param string[] $query_vars Public query variables.
	 * @return string[]
	 */
	public function add_query_var( array $query_vars ): array {
		$query_vars[] = self::QUERY_VAR;

		return $query_vars;
	}

	/**
	 * Serve the public llms.txt response.
	 *
	 * @return void
	 */
	public function serve_llms(): void {
		if (
			! self::is_enabled()
			|| '1' !== get_query_var( self::QUERY_VAR )
		) {
			return;
		}

		$content = $this->manifest->get_llms();
		$etag    = '"' . hash( 'sha256', $content ) . '"';
		header( 'ETag: ' . $etag );
		header( 'Cache-Control: public, max-age=' . Settings::get_cache_ttl() . ', must-revalidate' );
		header( 'X-Content-Type-Options: nosniff' );

		if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) && sanitize_text_field( wp_unslash( $_SERVER['HTTP_IF_NONE_MATCH'] ) ) === $etag ) {
			status_header( 304 );
			exit;
		}

		status_header( 200 );
		header(
			'Content-Type: text/plain; charset=' . get_bloginfo( 'charset' )
		);
		header( 'X-PressAgent-Resource: llms.txt' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain-text response generated by the plugin.

		exit;
	}
}
