name: Plugin Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  plugin-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: wordpress/plugin-check-action@v1
